name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  # Versi intl yang stabil saat ini adalah 0.19.0
  intl: ^0.20.2
  http: ^1.2.1 
  mqtt_client: ^9.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true